# Generated by Django 5.0.4 on 2024-04-24 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=255)),
                ('total_purchases', models.IntegerField(default=0)),
                ('average_receipt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('average_receipt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.category')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.place')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_receipts', to='analytics.product')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('transaction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nds_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tips_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=100)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='analytics.place')),
                ('products', models.ManyToManyField(through='analytics.ProductReceipt', to='analytics.product')),
            ],
        ),
        migrations.AddField(
            model_name='productreceipt',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_receipts', to='analytics.receipt'),
        ),
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_nds', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_tips', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='analytics.place')),
            ],
        ),
    ]
